name: prestatec01
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  image_gallery_saver_plus: ^4.0.0
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  image: ^4.0.17  # o la última versión
  qr: ^3.0.1
  barcode_widget: ^2.0.4
  flutter_barcode_listener: ^0.1.2
  mobile_scanner: ^5.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#edu gei